// ============================================
// JOB CONTROLLER — CRUD Operations for Jobs
// ============================================
// CRUD = Create, Read, Update, Delete — the four basic database operations.
//
// YOUR DIAGRAM — RECRUITER'S POV: Post a Job
// Form: { Job Title, Description, Min Requirements }
// POST /post-job → incoming req → create unique job id (UUID),
// job post timestamp → Store job details in Job Table/Collection
//
// YOUR DIAGRAM — CANDIDATE POV: Search for Jobs
// UI: keyword search + filters (S/W Dev 2 days ago, Infra Dev 3 days ago)
// POST → Backend/Search DB Query → Querying the DB
// ============================================

const Job = require('../models/Job');

// ============================================
// CREATE JOB — Recruiter posts a new job
// ============================================
// POST /api/jobs
// Body: { title, company, description, requirements, location, jobType, salary, skills, additionalDetails, deadline, openings }
//
// YOUR DIAGRAM: POST /post-job → { name, title, description, requirements, expires_in: 30 }
// ============================================
const createJob = async (req, res) => {
  try {
    const {
      title,
      company,
      description,
      requirements,
      location,
      jobType,
      salary,
      skills,
      additionalDetails,
      deadline,
      openings,
    } = req.body;

    // --- Validation ---
    if (!title || !description || !requirements || !location || !jobType) {
      return res.status(400).json({
        success: false,
        message:
          'Please provide title, description, requirements, location, and jobType.',
      });
    }

    // Create the job
    // postedBy is set to the currently logged-in recruiter (from auth middleware)
    // jobId (UUID) and createdAt (timestamp) are auto-generated by the model
    const job = await Job.create({
      title,
      company: company || req.user.company, // use recruiter's company if not provided
      description,
      requirements,
      location,
      jobType,
      salary,
      skills: skills || [],
      additionalDetails,
      deadline,
      openings,
      postedBy: req.user._id, // the logged-in recruiter's ID
    });

    res.status(201).json({
      success: true,
      message: 'Job posted successfully!',
      data: { job },
    });
  } catch (error) {
    console.error('Create job error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while creating job.',
      error: error.message,
    });
  }
};

// ============================================
// GET ALL JOBS — With search and filters
// ============================================
// GET /api/jobs?keyword=python&location=bangalore&jobType=internship&page=1&limit=10
//
// YOUR DIAGRAM — CANDIDATE POV:
// UI has: keyword search box + filter chips (S/W Dev, Infra Dev)
// → Backend/Search DB Query → Querying the DB
//
// HOW FILTERING WORKS:
// We build a "filter" object based on query parameters.
// MongoDB uses this filter to find matching documents.
// Example: { location: /bangalore/i, jobType: "internship" }
// means "find jobs in Bangalore that are internships"
// ============================================
const getAllJobs = async (req, res) => {
  try {
    const {
      keyword,
      location,
      jobType,
      skills,
      minSalary,
      maxSalary,
      status,
      page = 1,
      limit = 10,
      sortBy = 'createdAt',
      order = 'desc',
    } = req.query;

    // Build the filter object
    const filter = {};

    // --- Keyword search ---
    // YOUR DIAGRAM: "keyword ..." → search in title, description, requirements
    // We use $text search (enabled by the text index in Job model)
    // OR a regex-based search as fallback
    if (keyword) {
      // Use regex for flexible matching (case-insensitive)
      // This searches across title, description, requirements, and company
      filter.$or = [
        { title: { $regex: keyword, $options: 'i' } },
        { description: { $regex: keyword, $options: 'i' } },
        { requirements: { $regex: keyword, $options: 'i' } },
        { company: { $regex: keyword, $options: 'i' } },
        { skills: { $regex: keyword, $options: 'i' } },
      ];
    }

    // --- Location filter ---
    if (location) {
      filter.location = { $regex: location, $options: 'i' };
    }

    // --- Job type filter ---
    if (jobType) {
      filter.jobType = jobType;
    }

    // --- Skills filter ---
    // If multiple skills provided as comma-separated: "python,react,node"
    if (skills) {
      const skillsArray = skills.split(',').map((s) => s.trim());
      // $in means "match any of these values"
      filter.skills = { $in: skillsArray.map((s) => new RegExp(s, 'i')) };
    }

    // --- Status filter (default: only show open jobs) ---
    filter.status = status || 'open';

    // --- Pagination ---
    // "Skip" calculates how many documents to skip for the current page
    // Page 1: skip 0, Page 2: skip 10, Page 3: skip 20 (if limit=10)
    const skip = (parseInt(page) - 1) * parseInt(limit);

    // --- Sort ---
    const sortOptions = {};
    sortOptions[sortBy] = order === 'asc' ? 1 : -1;

    // --- Execute query ---
    const [jobs, totalCount] = await Promise.all([
      Job.find(filter)
        .populate('postedBy', 'name email company') // get recruiter details
        .sort(sortOptions)
        .skip(skip)
        .limit(parseInt(limit)),
      Job.countDocuments(filter), // total matching jobs (for pagination info)
    ]);

    res.status(200).json({
      success: true,
      data: {
        jobs,
        pagination: {
          currentPage: parseInt(page),
          totalPages: Math.ceil(totalCount / parseInt(limit)),
          totalJobs: totalCount,
          hasNextPage: skip + jobs.length < totalCount,
        },
      },
    });
  } catch (error) {
    console.error('Get all jobs error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while fetching jobs.',
      error: error.message,
    });
  }
};

// ============================================
// GET SINGLE JOB — By ID
// ============================================
// GET /api/jobs/:id
// ============================================
const getJobById = async (req, res) => {
  try {
    const job = await Job.findById(req.params.id).populate(
      'postedBy',
      'name email company phone'
    );

    if (!job) {
      return res.status(404).json({
        success: false,
        message: 'Job not found.',
      });
    }

    res.status(200).json({
      success: true,
      data: { job },
    });
  } catch (error) {
    console.error('Get job error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while fetching job.',
      error: error.message,
    });
  }
};

// ============================================
// GET MY JOBS — Recruiter sees their own posted jobs
// ============================================
// GET /api/jobs/my-jobs
// ============================================
const getMyJobs = async (req, res) => {
  try {
    const jobs = await Job.find({ postedBy: req.user._id }).sort({
      createdAt: -1,
    });

    res.status(200).json({
      success: true,
      data: { jobs, count: jobs.length },
    });
  } catch (error) {
    console.error('Get my jobs error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while fetching your jobs.',
      error: error.message,
    });
  }
};

// ============================================
// UPDATE JOB — Recruiter edits their job
// ============================================
// PUT /api/jobs/:id
// Only the recruiter who posted the job can update it
// ============================================
const updateJob = async (req, res) => {
  try {
    let job = await Job.findById(req.params.id);

    if (!job) {
      return res.status(404).json({
        success: false,
        message: 'Job not found.',
      });
    }

    // Check if the logged-in user is the one who posted the job
    if (job.postedBy.toString() !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        message: 'You can only update jobs that you posted.',
      });
    }

    // Update only the fields that were provided
    const allowedUpdates = [
      'title',
      'company',
      'description',
      'requirements',
      'location',
      'jobType',
      'salary',
      'skills',
      'additionalDetails',
      'deadline',
      'openings',
      'status',
    ];

    allowedUpdates.forEach((field) => {
      if (req.body[field] !== undefined) {
        job[field] = req.body[field];
      }
    });

    await job.save();

    res.status(200).json({
      success: true,
      message: 'Job updated successfully!',
      data: { job },
    });
  } catch (error) {
    console.error('Update job error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while updating job.',
      error: error.message,
    });
  }
};

// ============================================
// DELETE JOB — Recruiter deletes their job
// ============================================
// DELETE /api/jobs/:id
// Only the recruiter who posted the job can delete it
// ============================================
const deleteJob = async (req, res) => {
  try {
    const job = await Job.findById(req.params.id);

    if (!job) {
      return res.status(404).json({
        success: false,
        message: 'Job not found.',
      });
    }

    // Check ownership
    if (job.postedBy.toString() !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        message: 'You can only delete jobs that you posted.',
      });
    }

    await Job.findByIdAndDelete(req.params.id);

    res.status(200).json({
      success: true,
      message: 'Job deleted successfully!',
    });
  } catch (error) {
    console.error('Delete job error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while deleting job.',
      error: error.message,
    });
  }
};

module.exports = {
  createJob,
  getAllJobs,
  getJobById,
  getMyJobs,
  updateJob,
  deleteJob,
};
